name: Initialize Release

on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        description: "The branch to create the release from"
        default: "master"
        required: true
      releaseType:
        type: choice
        description: "Release type: major, minor, etc."
        required: true
        default: "patch"
        options:
          - major
          - minor
          - patch
          - prerelease
          - custom
      customVersion:
        type: string
        description: "Specified version. May include preids."
        default: ""
        required: false
      installDependencies:
        type: boolean
        description: "Install latest RokuCommunity dependencies"
        required: true
        default: true

jobs:
  run:
    uses: rokucommunity/workflows/.github/workflows/initialize-release.yml@develop
    with:
      branch: ${{ github.event.inputs.branch }}
      releaseType: ${{ github.event.inputs.releaseType }}
      preid: ${{ github.event.inputs.preid }}
      customVersion: ${{ github.event.inputs.customVersion }}
      installDependencies: ${{ github.event.inputs.installDependencies }}
      workflows-ref: ${{ 'develop' }}
    secrets: inherit
