name: Pre Build Release

on:
  pull_request:
    types:
        - closed
    paths:
        - 'package.json'
        - 'package-lock.json'

jobs:
  test:
    if: startsWith( github.head_ref, 'release/') && (github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    steps:
    - name: Testing
      run: echo "TESTING"
    